### ISSUE TITLE
Swift compile error. No such module. Zipfoundation error

### ISSUE THREAD

**Issue by memoli76** [tomkidd/Quake3-iOS#4]

**Comment by memoli76** [comment]
ZipFoundation.framework module is missing in your project. I still wonder why didnt you get this error while compiling

**Comment by cokete** [comment]
Same problem here.

Can you help us?

**Comment by Pash237** [comment]
Just do `carthage update` — it will compile ZipFoundation

**Comment by memoli76** [comment]
I did but no way. Could you share ipa without pak files

iPhone’umdan gönderildi

Pavel Alexeev <notifications@github.com> şunları yazdı (21 Nis 2020 01:08):

﻿

Just do carthage update — it will compile ZipFoundation

**Comment by tomkidd** [comment]
I have no idea why GitHub wasn't automatically telling me about these issues being posted. I'm now "watching" the repo so hopefully they start. 

Anyway like @Pash237 said, it was a Carthage issue however I just converted the project's dependencies to use Swift Package Manager (requires Xcode 11 I think) so this shouldn't happen anymore (i.e., no need to do Carthage)

**Comment by einzruff** [comment]
Just to note, after downloading the code and opening in Xcode, it threw the ZIPFoundation error and a FontAwesome 'failed with a non-zero exit' error too. (Xcode 12.0.1, set build to my iOS 14.0.1 8 Plus). I tried setting the toolchain in the Xcode menu from 'Swift 4.2.1 Release' to Xcode 12.0.1 and it built successfully. It showed a warning that "Options View Controller" is unreachable which is why I think the Settings menu isn't working in my case, but it is running well otherwise. Remember to login with an iCloud account in Preferences->Accounts, even if you don't have a paid developer account, then on the iPhone approve the app in Settings->General->Device Management.

**Comment by sbourji** [comment]
what did you mean by "setting the toolchain in the Xcode menu from 'Swift 4.2.1 Release' to 'Xcode 12.0.1' and it built successfully. " how?

**Comment by memoli76** [comment]
I have a jailbroken iphone. If you share your ipa without pak files, I can install it to my phone. Because my mac is too old to run new version of xcode

iPhone’umdan gönderildi

sbourji <notifications@github.com> şunları yazdı (26 Eki 2020 23:32):

﻿

what did you mean by "setting the toolchain in the Xcode menu from 'Swift 4.2.1 Release' to 'Xcode 12.0.1' and it built successfully. " how?

**Comment by sbourji** [comment]
I'm trying to compiled it for simulator, how can I sent you spa, when I cannot build it?

**Comment by memoli76** [comment]
Havent you compiled it yet?

iPhone’umdan gönderildi

sbourji <notifications@github.com> şunları yazdı (26 Eki 2020 23:40):

﻿

I'm trying to compiled it for simulator, how can I sent you spa, when I cannot build it?

**Comment by sbourji** [comment]
I'm using pod to install it on my system , and does work OK when I build for target, but get the No such module 'ZIPFoundation' for 'import ZIPFoundation' when compiled for simulator

**Comment by tomkidd** [comment]
The project no longer uses CocoaPods, I've removed that in favor of the Swift Package Manager. You should be able to have Xcode fetch the packages directly using Xcode 11 or later. 

If you're stuck using Xcode 10 there's a way to use SPM from the command line but I'm not familiar with how to do it. If you're truly stuck using an Xcode earlier than that then you're going to have to figure out how to get the project references in there some other way. 

The project and its maintenance are focused around using the latest tooling but I understand that some percentage of the audience is stuck using an older version of macOS/Xcode due to how Apple chooses to support older hardware.

**Comment by memoli76** [comment]
Thanks but i gave up using xcode. Can you share your .app or .ipa without pak files so that i can install to my jailbroken idevice

iPhone’umdan gönderildi

Tom Kidd <notifications@github.com> şunları yazdı (27 Eki 2020 14:34):

﻿

The project no longer uses CocoaPods, I've removed that in favor of the Swift Package Manager. You should be able to have Xcode fetch the packages directly using Xcode 11 or later.

If you're stuck using Xcode 10 there's a way to use SPM from the command line but I'm not familiar with how to do it. If you're truly stuck using an Xcode earlier than that then you're going to have to figure out how to get the project references in there some other way.

The project and its maintenance are focused around using the latest tooling but I understand that some percentage of the audience is stuck using an older version of macOS/Xcode due to how Apple chooses to support older hardware.

**Comment by sbourji** [comment]
I am using latest Xcode, it does compile for the iPhone device, but not for the simulator. Advise how to make Xcode use swift package, will be helpful. Thanks

Sent from my iPhone

On Oct 27, 2020, at 7:34 AM, Tom Kidd <notifications@github.com> wrote:

﻿

The project no longer uses CocoaPods, I've removed that in favor of the Swift Package Manager. You should be able to have Xcode fetch the packages directly using Xcode 11 or later.

If you're stuck using Xcode 10 there's a way to use SPM from the command line but I'm not familiar with how to do it. If you're truly stuck using an Xcode earlier than that then you're going to have to figure out how to get the project references in there some other way.

The project and its maintenance are focused around using the latest tooling but I understand that some percentage of the audience is stuck using an older version of macOS/Xcode due to how Apple chooses to support older hardware.

**Comment by memoli76** [comment]
I was able to manage for doom 3 but not for quake 3. So please share your ipa or app with me

iPhone’umdan gönderildi

sbourji <notifications@github.com> şunları yazdı (27 Eki 2020 15:10):

﻿

I am using latest Xcode, it does compile for the iPhone device, but not for the simulator. Advise how to make Xcode use swift package, will be helpful. Thanks

Sent from my iPhone

On Oct 27, 2020, at 7:34 AM, Tom Kidd <notifications@github.com> wrote:

﻿

The project no longer uses CocoaPods, I've removed that in favor of the Swift Package Manager. You should be able to have Xcode fetch the packages directly using Xcode 11 or later.

If you're stuck using Xcode 10 there's a way to use SPM from the command line but I'm not familiar with how to do it. If you're truly stuck using an Xcode earlier than that then you're going to have to figure out how to get the project references in there some other way.

The project and its maintenance are focused around using the latest tooling but I understand that some percentage of the audience is stuck using an older version of macOS/Xcode due to how Apple chooses to support older hardware.

**Comment by memoli76** [comment]
Write me step by step tutorial please but i use xcode 10

iPhone’umdan gönderildi

Mehmet Ali <m_a_guzel@hotmail.com> şunları yazdı (27 Eki 2020 15:29):

﻿ I was able to manage for doom 3 but not for quake 3. So please share your ipa or app with me

iPhone’umdan gönderildi

sbourji <notifications@github.com> şunları yazdı (27 Eki 2020 15:10):

﻿

I am using latest Xcode, it does compile for the iPhone device, but not for the simulator. Advise how to make Xcode use swift package, will be helpful. Thanks

Sent from my iPhone

On Oct 27, 2020, at 7:34 AM, Tom Kidd <notifications@github.com> wrote:

﻿

The project no longer uses CocoaPods, I've removed that in favor of the Swift Package Manager. You should be able to have Xcode fetch the packages directly using Xcode 11 or later.

If you're stuck using Xcode 10 there's a way to use SPM from the command line but I'm not familiar with how to do it. If you're truly stuck using an Xcode earlier than that then you're going to have to figure out how to get the project references in there some other way.

The project and its maintenance are focused around using the latest tooling but I understand that some percentage of the audience is stuck using an older version of macOS/Xcode due to how Apple chooses to support older hardware.

**Comment by sbourji** [comment]
Now that I switch to use the swift package I get the following when building for simulator
Could not find module 'ZIPFoundation' for target 'arm64-apple-ios-simulator'; found: x86_64-apple-ios-simulator, x86_6

**Comment by memoli76** [comment]
Do i need to xcode 11 to compile it or xcode 10 is enough?

iPhone’umdan gönderildi

sbourji <notifications@github.com> şunları yazdı (28 Eki 2020 15:04):

﻿

Now that I switch to use the swift package I get the following when building for simulator
Could not find module 'ZIPFoundation' for target 'arm64-apple-ios-simulator'; found: x86_64-apple-ios-simulator, x86_6

**Comment by memoli76** [comment]
I finally managed to compile using xcode 11 but after pressing one of these the game crash to homescreen[cid:B7007473-6A29-4E4D-B1D5-E5E36B600AA7-L0-001]

iPhone’umdan gönderildi

sbourji <notifications@github.com> şunları yazdı (28 Eki 2020 15:04):

﻿

Now that I switch to use the swift package I get the following when building for simulator
Could not find module 'ZIPFoundation' for target 'arm64-apple-ios-simulator'; found: x86_64-apple-ios-simulator, x86_6
